# Generated by Django 6.0.3 on 2026-06-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='users',
        ),
    ]
